# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/ArduinoSensorMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ArduinoSensorMsg(genpy.Message):
  _md5sum = "c40a1eb8516d96b4b9491e3444496b36"
  _type = "cobot_msgs/ArduinoSensorMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 time
float32 humidity
float32 temperature
float32 pressure
string sensorname

"""
  __slots__ = ['time','humidity','temperature','pressure','sensorname']
  _slot_types = ['float64','float32','float32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,humidity,temperature,pressure,sensorname

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArduinoSensorMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.humidity is None:
        self.humidity = 0.
      if self.temperature is None:
        self.temperature = 0.
      if self.pressure is None:
        self.pressure = 0.
      if self.sensorname is None:
        self.sensorname = ''
    else:
      self.time = 0.
      self.humidity = 0.
      self.temperature = 0.
      self.pressure = 0.
      self.sensorname = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_d3f().pack(_x.time, _x.humidity, _x.temperature, _x.pressure))
      _x = self.sensorname
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.time, _x.humidity, _x.temperature, _x.pressure,) = _get_struct_d3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sensorname = str[start:end].decode('utf-8')
      else:
        self.sensorname = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_d3f().pack(_x.time, _x.humidity, _x.temperature, _x.pressure))
      _x = self.sensorname
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.time, _x.humidity, _x.temperature, _x.pressure,) = _get_struct_d3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sensorname = str[start:end].decode('utf-8')
      else:
        self.sensorname = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d3f = None
def _get_struct_d3f():
    global _struct_d3f
    if _struct_d3f is None:
        _struct_d3f = struct.Struct("<d3f")
    return _struct_d3f
