# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/CobotStarGazerMarkerStatusMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cobot_msgs.msg
import genpy

class CobotStarGazerMarkerStatusMsg(genpy.Message):
  _md5sum = "46e0fbed8fbba7de6634c0991787f29d"
  _type = "cobot_msgs/CobotStarGazerMarkerStatusMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 id
CobotStarGazerMarkerMsg lastMsg
time firstSeen
uint16 count

================================================================================
MSG: cobot_msgs/CobotStarGazerMarkerMsg
uint16 ID
float32 rawX
float32 rawY
float32 rawOrientation

string map
float32 robotX
float32 robotY
float32 robotOrientation
"""
  __slots__ = ['id','lastMsg','firstSeen','count']
  _slot_types = ['uint16','cobot_msgs/CobotStarGazerMarkerMsg','time','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,lastMsg,firstSeen,count

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CobotStarGazerMarkerStatusMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.lastMsg is None:
        self.lastMsg = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      if self.firstSeen is None:
        self.firstSeen = genpy.Time()
      if self.count is None:
        self.count = 0
    else:
      self.id = 0
      self.lastMsg = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      self.firstSeen = genpy.Time()
      self.count = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H3f().pack(_x.id, _x.lastMsg.ID, _x.lastMsg.rawX, _x.lastMsg.rawY, _x.lastMsg.rawOrientation))
      _x = self.lastMsg.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f2IH().pack(_x.lastMsg.robotX, _x.lastMsg.robotY, _x.lastMsg.robotOrientation, _x.firstSeen.secs, _x.firstSeen.nsecs, _x.count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.lastMsg is None:
        self.lastMsg = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      if self.firstSeen is None:
        self.firstSeen = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.id, _x.lastMsg.ID, _x.lastMsg.rawX, _x.lastMsg.rawY, _x.lastMsg.rawOrientation,) = _get_struct_2H3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lastMsg.map = str[start:end].decode('utf-8')
      else:
        self.lastMsg.map = str[start:end]
      _x = self
      start = end
      end += 22
      (_x.lastMsg.robotX, _x.lastMsg.robotY, _x.lastMsg.robotOrientation, _x.firstSeen.secs, _x.firstSeen.nsecs, _x.count,) = _get_struct_3f2IH().unpack(str[start:end])
      self.firstSeen.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H3f().pack(_x.id, _x.lastMsg.ID, _x.lastMsg.rawX, _x.lastMsg.rawY, _x.lastMsg.rawOrientation))
      _x = self.lastMsg.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f2IH().pack(_x.lastMsg.robotX, _x.lastMsg.robotY, _x.lastMsg.robotOrientation, _x.firstSeen.secs, _x.firstSeen.nsecs, _x.count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.lastMsg is None:
        self.lastMsg = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      if self.firstSeen is None:
        self.firstSeen = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.id, _x.lastMsg.ID, _x.lastMsg.rawX, _x.lastMsg.rawY, _x.lastMsg.rawOrientation,) = _get_struct_2H3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lastMsg.map = str[start:end].decode('utf-8')
      else:
        self.lastMsg.map = str[start:end]
      _x = self
      start = end
      end += 22
      (_x.lastMsg.robotX, _x.lastMsg.robotY, _x.lastMsg.robotOrientation, _x.firstSeen.secs, _x.firstSeen.nsecs, _x.count,) = _get_struct_3f2IH().unpack(str[start:end])
      self.firstSeen.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H3f = None
def _get_struct_2H3f():
    global _struct_2H3f
    if _struct_2H3f is None:
        _struct_2H3f = struct.Struct("<2H3f")
    return _struct_2H3f
_struct_3f2IH = None
def _get_struct_3f2IH():
    global _struct_3f2IH
    if _struct_3f2IH is None:
        _struct_3f2IH = struct.Struct("<3f2IH")
    return _struct_3f2IH
