# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/CobotStarGazerVelMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cobot_msgs.msg
import std_msgs.msg

class CobotStarGazerVelMsg(genpy.Message):
  _md5sum = "5478352d59abfe6a0ebf618da5facf95"
  _type = "cobot_msgs/CobotStarGazerVelMsg"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
uint16 id
float32 vx
float32 vy
float32 vr

CobotStarGazerMarkerMsg msg1
CobotStarGazerMarkerMsg msg2

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: cobot_msgs/CobotStarGazerMarkerMsg
uint16 ID
float32 rawX
float32 rawY
float32 rawOrientation

string map
float32 robotX
float32 robotY
float32 robotOrientation
"""
  __slots__ = ['header','id','vx','vy','vr','msg1','msg2']
  _slot_types = ['std_msgs/Header','uint16','float32','float32','float32','cobot_msgs/CobotStarGazerMarkerMsg','cobot_msgs/CobotStarGazerMarkerMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,vx,vy,vr,msg1,msg2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CobotStarGazerVelMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.vr is None:
        self.vr = 0.
      if self.msg1 is None:
        self.msg1 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      if self.msg2 is None:
        self.msg2 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.vx = 0.
      self.vy = 0.
      self.vr = 0.
      self.msg1 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      self.msg2 = cobot_msgs.msg.CobotStarGazerMarkerMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_H3fH3f().pack(_x.id, _x.vx, _x.vy, _x.vr, _x.msg1.ID, _x.msg1.rawX, _x.msg1.rawY, _x.msg1.rawOrientation))
      _x = self.msg1.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3fH3f().pack(_x.msg1.robotX, _x.msg1.robotY, _x.msg1.robotOrientation, _x.msg2.ID, _x.msg2.rawX, _x.msg2.rawY, _x.msg2.rawOrientation))
      _x = self.msg2.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.msg2.robotX, _x.msg2.robotY, _x.msg2.robotOrientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.msg1 is None:
        self.msg1 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      if self.msg2 is None:
        self.msg2 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.id, _x.vx, _x.vy, _x.vr, _x.msg1.ID, _x.msg1.rawX, _x.msg1.rawY, _x.msg1.rawOrientation,) = _get_struct_H3fH3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.map = str[start:end].decode('utf-8')
      else:
        self.msg1.map = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.msg1.robotX, _x.msg1.robotY, _x.msg1.robotOrientation, _x.msg2.ID, _x.msg2.rawX, _x.msg2.rawY, _x.msg2.rawOrientation,) = _get_struct_3fH3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.map = str[start:end].decode('utf-8')
      else:
        self.msg2.map = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg2.robotX, _x.msg2.robotY, _x.msg2.robotOrientation,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_H3fH3f().pack(_x.id, _x.vx, _x.vy, _x.vr, _x.msg1.ID, _x.msg1.rawX, _x.msg1.rawY, _x.msg1.rawOrientation))
      _x = self.msg1.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3fH3f().pack(_x.msg1.robotX, _x.msg1.robotY, _x.msg1.robotOrientation, _x.msg2.ID, _x.msg2.rawX, _x.msg2.rawY, _x.msg2.rawOrientation))
      _x = self.msg2.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3f().pack(_x.msg2.robotX, _x.msg2.robotY, _x.msg2.robotOrientation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.msg1 is None:
        self.msg1 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      if self.msg2 is None:
        self.msg2 = cobot_msgs.msg.CobotStarGazerMarkerMsg()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.id, _x.vx, _x.vy, _x.vr, _x.msg1.ID, _x.msg1.rawX, _x.msg1.rawY, _x.msg1.rawOrientation,) = _get_struct_H3fH3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.map = str[start:end].decode('utf-8')
      else:
        self.msg1.map = str[start:end]
      _x = self
      start = end
      end += 26
      (_x.msg1.robotX, _x.msg1.robotY, _x.msg1.robotOrientation, _x.msg2.ID, _x.msg2.rawX, _x.msg2.rawY, _x.msg2.rawOrientation,) = _get_struct_3fH3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.map = str[start:end].decode('utf-8')
      else:
        self.msg2.map = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg2.robotX, _x.msg2.robotY, _x.msg2.robotOrientation,) = _get_struct_3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_H3fH3f = None
def _get_struct_H3fH3f():
    global _struct_H3fH3f
    if _struct_H3fH3f is None:
        _struct_H3fH3f = struct.Struct("<H3fH3f")
    return _struct_H3fH3f
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_3fH3f = None
def _get_struct_3fH3f():
    global _struct_3fH3f
    if _struct_3fH3f is None:
        _struct_3fH3f = struct.Struct("<3fH3f")
    return _struct_3fH3f
