# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/CobotWifiMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CobotWifiMsg(genpy.Message):
  _md5sum = "b9f582464469da5aa0a4b3c226831cbc"
  _type = "cobot_msgs/CobotWifiMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 rssi
uint64 bssid
string ssid
float64 age
"""
  __slots__ = ['rssi','bssid','ssid','age']
  _slot_types = ['float32','uint64','string','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rssi,bssid,ssid,age

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CobotWifiMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.rssi is None:
        self.rssi = 0.
      if self.bssid is None:
        self.bssid = 0
      if self.ssid is None:
        self.ssid = ''
      if self.age is None:
        self.age = 0.
    else:
      self.rssi = 0.
      self.bssid = 0
      self.ssid = ''
      self.age = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_fQ().pack(_x.rssi, _x.bssid))
      _x = self.ssid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_d().pack(self.age))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.rssi, _x.bssid,) = _get_struct_fQ().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ssid = str[start:end].decode('utf-8')
      else:
        self.ssid = str[start:end]
      start = end
      end += 8
      (self.age,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_fQ().pack(_x.rssi, _x.bssid))
      _x = self.ssid
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_d().pack(self.age))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.rssi, _x.bssid,) = _get_struct_fQ().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ssid = str[start:end].decode('utf-8')
      else:
        self.ssid = str[start:end]
      start = end
      end += 8
      (self.age,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fQ = None
def _get_struct_fQ():
    global _struct_fQ
    if _struct_fQ is None:
        _struct_fQ = struct.Struct("<fQ")
    return _struct_fQ
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
