# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/DistanceSensorMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DistanceSensorMsg(genpy.Message):
  _md5sum = "f8453724d94262f523965e6ca0fd3606"
  _type = "cobot_msgs/DistanceSensorMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 time
uint16 raw
float32 volts
#range in cm
float32 range_cm
"""
  __slots__ = ['time','raw','volts','range_cm']
  _slot_types = ['float64','uint16','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,raw,volts,range_cm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DistanceSensorMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.raw is None:
        self.raw = 0
      if self.volts is None:
        self.volts = 0.
      if self.range_cm is None:
        self.range_cm = 0.
    else:
      self.time = 0.
      self.raw = 0
      self.volts = 0.
      self.range_cm = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dH2f().pack(_x.time, _x.raw, _x.volts, _x.range_cm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.time, _x.raw, _x.volts, _x.range_cm,) = _get_struct_dH2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dH2f().pack(_x.time, _x.raw, _x.volts, _x.range_cm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.time, _x.raw, _x.volts, _x.range_cm,) = _get_struct_dH2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dH2f = None
def _get_struct_dH2f():
    global _struct_dH2f
    if _struct_dH2f is None:
        _struct_dH2f = struct.Struct("<dH2f")
    return _struct_dH2f
