# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/MotionModel2D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cobot_msgs.msg

class MotionModel2D(genpy.Message):
  _md5sum = "995516e3ff6917e85e659ea708676699"
  _type = "cobot_msgs/MotionModel2D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """cobot_msgs/AccelerationLimits translation
cobot_msgs/AccelerationLimits rotation

================================================================================
MSG: cobot_msgs/AccelerationLimits
float32 max_acceleration
float32 max_speed
"""
  __slots__ = ['translation','rotation']
  _slot_types = ['cobot_msgs/AccelerationLimits','cobot_msgs/AccelerationLimits']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       translation,rotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotionModel2D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.translation is None:
        self.translation = cobot_msgs.msg.AccelerationLimits()
      if self.rotation is None:
        self.rotation = cobot_msgs.msg.AccelerationLimits()
    else:
      self.translation = cobot_msgs.msg.AccelerationLimits()
      self.rotation = cobot_msgs.msg.AccelerationLimits()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.translation.max_acceleration, _x.translation.max_speed, _x.rotation.max_acceleration, _x.rotation.max_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.translation is None:
        self.translation = cobot_msgs.msg.AccelerationLimits()
      if self.rotation is None:
        self.rotation = cobot_msgs.msg.AccelerationLimits()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.translation.max_acceleration, _x.translation.max_speed, _x.rotation.max_acceleration, _x.rotation.max_speed,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.translation.max_acceleration, _x.translation.max_speed, _x.rotation.max_acceleration, _x.rotation.max_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.translation is None:
        self.translation = cobot_msgs.msg.AccelerationLimits()
      if self.rotation is None:
        self.rotation = cobot_msgs.msg.AccelerationLimits()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.translation.max_acceleration, _x.translation.max_speed, _x.rotation.max_acceleration, _x.rotation.max_speed,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
