# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/CobotTaskPlannerStatusSrvRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import cobot_msgs.msg

class CobotTaskPlannerStatusSrvRequest(genpy.Message):
  _md5sum = "d54d29cd25c74ea5306e9143d9b80042"
  _type = "cobot_msgs/CobotTaskPlannerStatusSrvRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """CobotTaskPlannerMsg msg


================================================================================
MSG: cobot_msgs/CobotTaskPlannerMsg
int32 mission_id
string currentTask
string currentSubTask
string currentNavigationSubTask
float32 timeBlocked
float32 taskDuration
float32 subTaskDuration
float32 navigationSubTaskDuration
float32 navigationTimeRemaining
float32 timeToDeadline

CobotLocalizationMsg currentDestination
string fromLocation
string toLocation
string objectToFind

bool carryingObject
bool navigating
bool taskCompleted
int32 successValue

bool paused
string owner

================================================================================
MSG: cobot_msgs/CobotLocalizationMsg
float64 timeStamp
float32 x
float32 y
float32 angle
float32 angleUncertainty
float32 locationUncertainty
string map

float64 lastLaserRunTime
float64 laserRunTime
int32 laserNumObservedPoints
int32 laserNumCorrespondences
float32 laserStage0Weights
float32 laserStageRWeights
float32 laserMeanSqError

float64 lastPointCloudRunTime
float64 pointCloudRunTime
int32 pointCloudNumObservedPoints
int32 pointCloudNumCorrespondences
float32 pointCloudStage0Weights
float32 pointCloudStageRWeights
float32 pointCloudMeanSqError

"""
  __slots__ = ['msg']
  _slot_types = ['cobot_msgs/CobotTaskPlannerMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CobotTaskPlannerStatusSrvRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.msg is None:
        self.msg = cobot_msgs.msg.CobotTaskPlannerMsg()
    else:
      self.msg = cobot_msgs.msg.CobotTaskPlannerMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_i().pack(self.msg.mission_id))
      _x = self.msg.currentTask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.currentSubTask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.currentNavigationSubTask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6fd5f().pack(_x.msg.timeBlocked, _x.msg.taskDuration, _x.msg.subTaskDuration, _x.msg.navigationSubTaskDuration, _x.msg.navigationTimeRemaining, _x.msg.timeToDeadline, _x.msg.currentDestination.timeStamp, _x.msg.currentDestination.x, _x.msg.currentDestination.y, _x.msg.currentDestination.angle, _x.msg.currentDestination.angleUncertainty, _x.msg.currentDestination.locationUncertainty))
      _x = self.msg.currentDestination.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2d2i3f2d2i3f().pack(_x.msg.currentDestination.lastLaserRunTime, _x.msg.currentDestination.laserRunTime, _x.msg.currentDestination.laserNumObservedPoints, _x.msg.currentDestination.laserNumCorrespondences, _x.msg.currentDestination.laserStage0Weights, _x.msg.currentDestination.laserStageRWeights, _x.msg.currentDestination.laserMeanSqError, _x.msg.currentDestination.lastPointCloudRunTime, _x.msg.currentDestination.pointCloudRunTime, _x.msg.currentDestination.pointCloudNumObservedPoints, _x.msg.currentDestination.pointCloudNumCorrespondences, _x.msg.currentDestination.pointCloudStage0Weights, _x.msg.currentDestination.pointCloudStageRWeights, _x.msg.currentDestination.pointCloudMeanSqError))
      _x = self.msg.fromLocation
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.toLocation
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.objectToFind
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3BiB().pack(_x.msg.carryingObject, _x.msg.navigating, _x.msg.taskCompleted, _x.msg.successValue, _x.msg.paused))
      _x = self.msg.owner
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.msg is None:
        self.msg = cobot_msgs.msg.CobotTaskPlannerMsg()
      end = 0
      start = end
      end += 4
      (self.msg.mission_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentTask = str[start:end].decode('utf-8')
      else:
        self.msg.currentTask = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentSubTask = str[start:end].decode('utf-8')
      else:
        self.msg.currentSubTask = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentNavigationSubTask = str[start:end].decode('utf-8')
      else:
        self.msg.currentNavigationSubTask = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.msg.timeBlocked, _x.msg.taskDuration, _x.msg.subTaskDuration, _x.msg.navigationSubTaskDuration, _x.msg.navigationTimeRemaining, _x.msg.timeToDeadline, _x.msg.currentDestination.timeStamp, _x.msg.currentDestination.x, _x.msg.currentDestination.y, _x.msg.currentDestination.angle, _x.msg.currentDestination.angleUncertainty, _x.msg.currentDestination.locationUncertainty,) = _get_struct_6fd5f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentDestination.map = str[start:end].decode('utf-8')
      else:
        self.msg.currentDestination.map = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.msg.currentDestination.lastLaserRunTime, _x.msg.currentDestination.laserRunTime, _x.msg.currentDestination.laserNumObservedPoints, _x.msg.currentDestination.laserNumCorrespondences, _x.msg.currentDestination.laserStage0Weights, _x.msg.currentDestination.laserStageRWeights, _x.msg.currentDestination.laserMeanSqError, _x.msg.currentDestination.lastPointCloudRunTime, _x.msg.currentDestination.pointCloudRunTime, _x.msg.currentDestination.pointCloudNumObservedPoints, _x.msg.currentDestination.pointCloudNumCorrespondences, _x.msg.currentDestination.pointCloudStage0Weights, _x.msg.currentDestination.pointCloudStageRWeights, _x.msg.currentDestination.pointCloudMeanSqError,) = _get_struct_2d2i3f2d2i3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.fromLocation = str[start:end].decode('utf-8')
      else:
        self.msg.fromLocation = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.toLocation = str[start:end].decode('utf-8')
      else:
        self.msg.toLocation = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.objectToFind = str[start:end].decode('utf-8')
      else:
        self.msg.objectToFind = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg.carryingObject, _x.msg.navigating, _x.msg.taskCompleted, _x.msg.successValue, _x.msg.paused,) = _get_struct_3BiB().unpack(str[start:end])
      self.msg.carryingObject = bool(self.msg.carryingObject)
      self.msg.navigating = bool(self.msg.navigating)
      self.msg.taskCompleted = bool(self.msg.taskCompleted)
      self.msg.paused = bool(self.msg.paused)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.owner = str[start:end].decode('utf-8')
      else:
        self.msg.owner = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_i().pack(self.msg.mission_id))
      _x = self.msg.currentTask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.currentSubTask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.currentNavigationSubTask
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_6fd5f().pack(_x.msg.timeBlocked, _x.msg.taskDuration, _x.msg.subTaskDuration, _x.msg.navigationSubTaskDuration, _x.msg.navigationTimeRemaining, _x.msg.timeToDeadline, _x.msg.currentDestination.timeStamp, _x.msg.currentDestination.x, _x.msg.currentDestination.y, _x.msg.currentDestination.angle, _x.msg.currentDestination.angleUncertainty, _x.msg.currentDestination.locationUncertainty))
      _x = self.msg.currentDestination.map
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2d2i3f2d2i3f().pack(_x.msg.currentDestination.lastLaserRunTime, _x.msg.currentDestination.laserRunTime, _x.msg.currentDestination.laserNumObservedPoints, _x.msg.currentDestination.laserNumCorrespondences, _x.msg.currentDestination.laserStage0Weights, _x.msg.currentDestination.laserStageRWeights, _x.msg.currentDestination.laserMeanSqError, _x.msg.currentDestination.lastPointCloudRunTime, _x.msg.currentDestination.pointCloudRunTime, _x.msg.currentDestination.pointCloudNumObservedPoints, _x.msg.currentDestination.pointCloudNumCorrespondences, _x.msg.currentDestination.pointCloudStage0Weights, _x.msg.currentDestination.pointCloudStageRWeights, _x.msg.currentDestination.pointCloudMeanSqError))
      _x = self.msg.fromLocation
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.toLocation
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.msg.objectToFind
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3BiB().pack(_x.msg.carryingObject, _x.msg.navigating, _x.msg.taskCompleted, _x.msg.successValue, _x.msg.paused))
      _x = self.msg.owner
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.msg is None:
        self.msg = cobot_msgs.msg.CobotTaskPlannerMsg()
      end = 0
      start = end
      end += 4
      (self.msg.mission_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentTask = str[start:end].decode('utf-8')
      else:
        self.msg.currentTask = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentSubTask = str[start:end].decode('utf-8')
      else:
        self.msg.currentSubTask = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentNavigationSubTask = str[start:end].decode('utf-8')
      else:
        self.msg.currentNavigationSubTask = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.msg.timeBlocked, _x.msg.taskDuration, _x.msg.subTaskDuration, _x.msg.navigationSubTaskDuration, _x.msg.navigationTimeRemaining, _x.msg.timeToDeadline, _x.msg.currentDestination.timeStamp, _x.msg.currentDestination.x, _x.msg.currentDestination.y, _x.msg.currentDestination.angle, _x.msg.currentDestination.angleUncertainty, _x.msg.currentDestination.locationUncertainty,) = _get_struct_6fd5f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.currentDestination.map = str[start:end].decode('utf-8')
      else:
        self.msg.currentDestination.map = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.msg.currentDestination.lastLaserRunTime, _x.msg.currentDestination.laserRunTime, _x.msg.currentDestination.laserNumObservedPoints, _x.msg.currentDestination.laserNumCorrespondences, _x.msg.currentDestination.laserStage0Weights, _x.msg.currentDestination.laserStageRWeights, _x.msg.currentDestination.laserMeanSqError, _x.msg.currentDestination.lastPointCloudRunTime, _x.msg.currentDestination.pointCloudRunTime, _x.msg.currentDestination.pointCloudNumObservedPoints, _x.msg.currentDestination.pointCloudNumCorrespondences, _x.msg.currentDestination.pointCloudStage0Weights, _x.msg.currentDestination.pointCloudStageRWeights, _x.msg.currentDestination.pointCloudMeanSqError,) = _get_struct_2d2i3f2d2i3f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.fromLocation = str[start:end].decode('utf-8')
      else:
        self.msg.fromLocation = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.toLocation = str[start:end].decode('utf-8')
      else:
        self.msg.toLocation = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.objectToFind = str[start:end].decode('utf-8')
      else:
        self.msg.objectToFind = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg.carryingObject, _x.msg.navigating, _x.msg.taskCompleted, _x.msg.successValue, _x.msg.paused,) = _get_struct_3BiB().unpack(str[start:end])
      self.msg.carryingObject = bool(self.msg.carryingObject)
      self.msg.navigating = bool(self.msg.navigating)
      self.msg.taskCompleted = bool(self.msg.taskCompleted)
      self.msg.paused = bool(self.msg.paused)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg.owner = str[start:end].decode('utf-8')
      else:
        self.msg.owner = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_2d2i3f2d2i3f = None
def _get_struct_2d2i3f2d2i3f():
    global _struct_2d2i3f2d2i3f
    if _struct_2d2i3f2d2i3f is None:
        _struct_2d2i3f2d2i3f = struct.Struct("<2d2i3f2d2i3f")
    return _struct_2d2i3f2d2i3f
_struct_6fd5f = None
def _get_struct_6fd5f():
    global _struct_6fd5f
    if _struct_6fd5f is None:
        _struct_6fd5f = struct.Struct("<6fd5f")
    return _struct_6fd5f
_struct_3BiB = None
def _get_struct_3BiB():
    global _struct_3BiB
    if _struct_3BiB is None:
        _struct_3BiB = struct.Struct("<3BiB")
    return _struct_3BiB
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cobot_msgs/CobotTaskPlannerStatusSrvResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CobotTaskPlannerStatusSrvResponse(genpy.Message):
  _md5sum = "f836c04ce7c82d87a10dab08ba90a2d2"
  _type = "cobot_msgs/CobotTaskPlannerStatusSrvResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
int32 received

"""
  __slots__ = ['received']
  _slot_types = ['int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       received

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CobotTaskPlannerStatusSrvResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.received is None:
        self.received = 0
    else:
      self.received = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_i().pack(self.received))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.received,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_i().pack(self.received))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.received,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
class CobotTaskPlannerStatusSrv(object):
  _type          = 'cobot_msgs/CobotTaskPlannerStatusSrv'
  _md5sum = '7b090f2cb660cbf515beffee82d8a057'
  _request_class  = CobotTaskPlannerStatusSrvRequest
  _response_class = CobotTaskPlannerStatusSrvResponse
